### ISSUE TITLE
Importing getch is a different procedure than what's written in the readme

### ISSUE THREAD

**Issue by GijsTimmers** [joeyespo/py-getch#1]
Current situation in README:

```
from getch import getch, pause

key = getch()
print 'You pressed:', key
pause()
```

This doesn't work:

```
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from getch import getch, pause
>>> key = getch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

This does:

```
>>> from getch.getch import getch
>>> key = getch()
>>>
```

or:

```
>>> import getch.getch
>>> key = getch.getch.getch()
>>>
```

**Comment by GijsTimmers** [comment]
Also, thanks for writing `getch`, it's really useful!

**Comment by joeyespo** [comment]
Whoops, you're right. Looks like version 0.1.0 was never published to PyPI. [Just published](https://pypi.python.org/pypi?:action=display&name=py-getch&version=0.1.0).

I haven't touched this project in a couple years. Thanks for pointing that out @GijsTimmers! And Glad you find it useful :smiley:
