### ISSUE TITLE
getch.getch() gives unreliable data on some keypresses

### ISSUE THREAD

**Issue by GijsTimmers** [joeyespo/py-getch#3]
Using Ubuntu 14.04, py-getch 0.1.0.

Demonstration:

```
$ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from getch import getch
>>> getch() ## Now press F5
'\x1b'
>>> getch() ## Now press nothing. getch() returns a character 'automatically'.
'['
>>> getch() ## This happens a couple of times...
'1'
>>> getch() ## ...
'5'
>>> getch() ## ...
'~'
>>> getch() ## ... and then, getch() gets back to normal behaviour.
```

I know that it happens for the F-keys and for the arrow keys. Maybe other keys are affected as well.

**Comment by wolmir** [comment]
This is not unreliable data. Special keys are represented by more than one character.
In Windows, a function key press will return '\xe0' and the next call to getch() will return the key code.

In UNIX systems, they will return '\x1b', and the next **two** getch() calls will return the key code.
Pressing F5, for instance, will return '\x1b', then '[', and, finally, '1'. You can learn more about how these
characters are treated by UNIX terminals here: https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by GijsTimmers** [comment]
I see. Thanks for clarifying!

**Comment by joeyespo** [comment]
@wolmir Thanks for jumping in! :+1:

**Comment by mo-han** [comment]
@joeyespo
Sorry to dig out this issue if borthering you guys, but how to handle or distinguish those special fn key pressing in a correct way? Use a queue or a buffer with some "incremental decoder" to detect the "returned bytes context"?
I know it's an old and stable library, but maybe it's OK to add something to it?
