### ISSUE TITLE
pause_exit isn't being imported, but pause and getch are

### ISSUE THREAD

**Issue by Gmanicus** [joeyespo/py-getch#7]
Sorry for digging up an issue for something you haven't updated in years.

For some reason, pause_exit(status, message) is not working for me. I imported everything as shown in the docs, and even tried editing the source code, but it doesn't want to work.

**Comment by porter707** [comment]
Hi,

The docs don't provide an example for importing pause_exit()

You need to add pause_exit to your import line e.g

`from getch import getch, pause, pause_exit`

or 

`from getch import pause_exit`

both work for me.

**Comment by Gmanicus** [comment]
Oh, lol, why didn't I try that? Thanks!

**Comment by joeyespo** [comment]
Thanks for chiming in, @porter707! 😃 

I know it can be frustrating when example code doens't run out-of-the-box. I just tweaked the example in the Readme to hopefully help anyone else who comes across this.

Thanks for the issue & for using Py-Getch!
